### ISSUE TITLE
Unable to add new radio stations 

### ISSUE THREAD

**Issue by MiAutomations** [RASPIAUDIO/MuseRadio-DEMO#1]
Hello

I try to add the following links to the muse radio from the QR code reader and over the site, I created a new radio stations entries, but none of the stations/links working and the muse radio starts restarting after the links added  

https://stream-icy.bauermedia.pt/comercial.aac
https://stream-icy.bauermedia.pt/comercial.mp3 
https://stream-icy.bauermedia.pt/m8080.aac

Is there anything to do in order to try to solve this issue?

**Comment by RASPIAUDIO** [comment]
use the same urls but in http, not https.
I've tried http://stream-icy.bauermedia.pt/comercial.mp3 and it is working

**Comment by MiAutomations** [comment]
> http://stream-icy.bauermedia.pt/comercial.mp3

Hello I try to add the link without HTTPS instead I use the HTTP as you mentioned and i use this link also to test:
[http://stream-icy.bauermedia.pt/comercial.mp3 ](url)
![image](https://github.com/user-attachments/assets/aa010c21-26bc-4488-993f-450001a059dd)

But I still facing a reboots from the muse radio after this change/adding this new station

Can you please check ? 
Thank you

**Comment by RASPIAUDIO** [comment]
Please send me your logs, on apps.raspiaudio.com lauch the serial monitor and click on reboot

**Comment by MiAutomations** [comment]
> apps.raspiaudio.com

the log file, I removed the wifi credentials 


WiFi

WiFi connected:  -46
Récupération de la liste des stations à partir de: https://raspiaudio.com/radio/radio.php?serial=24587CD5DAE0&action=get
Code retour HTTP GET : 200
Payload reçu :
[{"name":"Radio Comercial ","url":"http:\/\/stream-icy.bauermedia.pt\/comercial.mp3"}]
Liste des stations mise à jour depuis le serveur
Codec init OK
Jack OFF
=========> 1 
station = 2    vol = 4
/screenV.png
image specs: (240 x 320), 8 bpp, pixel type: 6
drawImage end
>>>> 4
ESP-ROM:esp32s3-20210327
Build:Mar 27 2021
rst:0x15 (USB_UART_CHIP_RESET),boot:0x2b (SPI_FAST_FLASH_BOOT)
Saved PC:0x40381101
SPIWP:0xee
mode:DIO, clock div:1
load:0x3fce3808,len:0x44c
load:0x403c9700,len:0xbd8
load:0x403cc700,len:0x2a80
entry 0x403c98d0
FILE: /QR
FILE: /Raspiaudio.png
FILE: /linkS
FILE: /mode
FILE: /nameS
FILE: /pwd
FILE: /screenV.png
FILE: /ssid
FILE: /station
FILE: /volume
mode = 1
screen init...
/Raspiaudio.png
image specs: (320 x 240), 8 bpp, pixel type: 6
drawImage end
WiFi
KK-HOME    Vick20asd.-2774064
WiFi connected: KK-HOME -47
Récupération de la liste des stations à partir de: https://raspiaudio.com/radio/radio.php?serial=24587CD5DAE0&action=get
Code retour HTTP GET : 200
Payload reçu :
[{"name":"Radio Comercial ","url":"http:\/\/stream-icy.bauermedia.pt\/comercial.mp3"}]
Liste des stations mise à jour depuis le serveur
Codec init OK
Jack OFF
=========> 1 
station = 2    vol = 4
/screenV.png
image specs: (240 x 320), 8 bpp, pixel type: 6
drawImage end
>>>> 4
E (28644) task_wdt: Task watchdog got triggered. The following tasks did not reset the watchdog in time:
E (28644) task_wdt:  - IDLE (CPU 0)
E (28644) task_wdt: Tasks currently running:
E (28644) task_wdt: CPU 0: radio
E (28644) task_wdt: CPU 1: loopTask
E (28644) task_wdt: Aborting.

abort() was called at PC 0x420545c0 on core 0


Backtrace: 0x403782d2:0x3fc96e60 0x4037dd8d:0x3fc96e80 0x40383d01:0x3fc96ea0 0x420545c0:0x3fc96f20 0x40379951:0x3fc96f40 0x4037edbb:0x3fcd9d00 0x4037ef28:0x3fcd9d40 0x40379c1d:0x3fcd9d60 0x40379cf5:0x3fcd9d90 0x40379dc4:0x3fcd9db0 0x420e3756:0x3fcd9de0 0x420e3815:0x3fcd9e20 0x4202906f:0x3fcd9e40 0x42028d9f:0x3fcd9e60 0x420048d1:0x3fcd9e80 0x420075b8:0x3fcd9ec0




ELF file SHA256: 56ecdcad580224c3

Rebooting...
ESP-ROM:esp32s3-20210327
Build:Mar 27 2021
rst:0xc (RTC_SW_CPU_RST),boot:0x2b (SPI_FAST_FLASH_BOOT)
Saved PC:0x40377ee0
SPIWP:0xee
mode:DIO, clock div:1
load:0x3fce3808,len:0x44c
load:0x403c9700,len:0xbd8
load:0x403cc700,len:0x2a80
entry 0x403c98d0
FILE: /QR
FILE: /Raspiaudio.png
FILE: /linkS
FILE: /mode
FILE: /nameS
FILE: /pwd
FILE: /screenV.png
FILE: /ssid
FILE: /station
FILE: /volume
mode = 1
screen init...
/Raspiaudio.png
image specs: (320 x 240), 8 bpp, pixel type: 6
drawImage end
WiFi

**Comment by RASPIAUDIO** [comment]
ok got it "station = 2"
quick fix : try to add 3 stations in your list

Explanation : as the index for last station played is 2, then you removed one station from your list it is trying to play something that does not exist

I need to update the code soon
